/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : PIT.h
**     Project     : ProcessorExpert
**     Processor   : MKL25Z64VLK4
**     Component   : Init_PIT
**     Version     : Component 01.004, Driver 01.04, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-09-24, 21:11, # CodeGen: 11
**     Abstract    :
**          This file implements the PIT (PIT) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
**     Settings    :
**          Component name                                 : PIT
**          Device                                         : PIT
**          Setttings                                      : 
**            Clock gate                                   : Enabled
**            Clock settings                               : 
**              Base clock frequency                       : 24 MHz
**            Freeze in debug mode                         : no
**          Channels                                       : 
**            Channel 0                                    : 
**              Timer 0                                    : Enabled
**              Timer 0 load value                         : 23999
**              Timer 0 Period                             : 1 ms
**              Interrupt                                  : 
**                Interrupt                                : INT_PIT
**                Interrupt request                        : Enabled
**                Interrupt priority                       : 0 (Highest)
**                ISR Name                                 : TEST_IRQ
**                Timer interrupt                          : Enabled
**            Channel 1                                    : 
**              Timer 1                                    : Disabled
**              Timer 1 chain mode                         : Disabled
**              Timer 1 load value                         : 0
**              Timer 1 Period                             : 0.042 us
**              Interrupt                                  : 
**                Interrupt                                : INT_PIT
**                Interrupt request                        : Enabled
**                Interrupt priority                       : 0 (Highest)
**                ISR Name                                 : <Automatic>
**                Timer interrupt                          : Disabled
**          Initialization                                 : 
**            Module                                       : Disabled
**            Call Init method                             : no
**     Contents    :
**         Init - void PIT_Init(void);
**
**     Copyright : 1997 - 2013 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file PIT.h
** @version 01.04
** @brief
**          This file implements the PIT (PIT) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
*/         
/*!
**  @addtogroup PIT_module PIT module documentation
**  @{
*/         

#ifndef PIT_H_
#define PIT_H_

/* MODULE PIT. */

/* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"

/* Peripheral base address parameter */
#define PIT_DEVICE PIT_BASE_PTR


/*
** ===================================================================
**     Method      :  PIT_Init (component Init_PIT)
**     Description :
**         This method initializes registers of the PIT module
**         according to the Peripheral Initialization settings.
**         Call this method in user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void PIT_Init(void);
/*
** ===================================================================
** The interrupt service routine must be implemented by user in one
** of the user modules (see PIT.c file for more information).
** ===================================================================
*/
PE_ISR(TEST_IRQ);
/*
** ===================================================================
** The interrupt service routine must be implemented by user in one
** of the user modules (see PIT.c file for more information).
** ===================================================================
*/
PE_ISR(TEST_IRQ);


/* END PIT. */
#endif /* #ifndef __PIT_H_ */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.08]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
