/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : UART0_Config.h
**     Project     : MarqDroneMK22FN
**     Processor   : MK22FN512VLH12
**     Component   : Init_UART
**     Version     : Component 01.007, Driver 01.07, CPU db: 3.00.000
**     Repository  : Kinetis
**     Compiler    : GNU C Compiler
**     Date/Time   : 2016-05-19, 17:29, # CodeGen: 54
**     Abstract    :
**          This file implements the UART (UART0) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
**     Settings    :
**          Component name                                 : UART0
**          Device                                         : UART0
**          Settings                                       : 
**            Clock gate                                   : Enabled
**            Clock settings                               : 
**              Baud rate divisor                          : 65
**              Baud rate fine adjust                      : 3
**              Baud rate                                  : 115218.435 baud
**            Transfer settings                            : 
**              Data format                                : 8bit
**              Bits ordering                              : LSB first
**              Parity                                     : Off
**              Stop bit number                            : 1
**              Parity placement                           : Parity in last data bit
**            Idle character counting                      : After start bit
**            Break character generation length            : Short
**            LIN Break detection                          : Disabled
**            Stop in Wait mode                            : Disabled
**            Receiver wakeup settings                     : 
**              Receiver wakeup                            : Normal operation
**              Receiver wake up method                    : Idle-line
**              Receive wakeup idle detect                 : Don't set IDLE bit
**              Match address settings                     : 
**                Match address 1                          : Disabled
**                Match address 1 value                    : 0
**                Match address 2                          : Disabled
**                Match address 2 value                    : 0
**            Modem settings                               : 
**              Tx CTS                                     : Disabled
**              Tx RTS                                     : Disabled
**              Tx RTS polarity                            : Active low
**              Rx RTS                                     : Disabled
**            Infrared settings                            : 
**              Infrared                                   : Disabled
**              Tx narrow pulse width                      : 3/16
**            FIFOs settings                               : 
**              Tx FIFO                                    : Disabled
**              Tx watermark                               : 0
**              Rx FIFO                                    : Disabled
**              Rx watermark                               : 1
**            Smartcards interface (ISO7816) settings      : 
**              ISO7816 functionality                      : Disabled
**              Transfer type                              : T=0
**                Rx error action                          : Error NACK not generated
**                Rx FIFO overflow action                  : Overflow NACK not generated
**                Rx NACK threshold                        : 0
**                Tx NACK threshold                        : 0
**                Answer to reset duration time parameter  : 0
**                Wait time parameter                      : 20
**              Init char detection                        : Disabled
**              Guard band N                               : 0
**              FD multiplier                              : 1
**            Loops and Single wire settings               : 
**              Loop mode                                  : Disabled
**              Receiver source in Loop mode               : Loop mode
**              TxD pin direction in Single-wire mode      : Input
**            Receiver input                               : Not inverted
**            Transmitter output                           : Not inverted
**          Pins/Signals                                   : 
**            Receiver pin                                 : Enabled
**              Pin                                        : PTB16/SPI1_SOUT/UART0_RX/FTM_CLKIN0/FBa_AD17/EWM_IN
**            Transmitter pin                              : Enabled
**              Pin                                        : PTB17/SPI1_SIN/UART0_TX/FTM_CLKIN1/FBa_AD16/EWM_OUT_b
**              Transmitter modulation                     : Disabled
**            CTS pin                                      : Disabled
**            RTS pin                                      : Disabled
**          Interrupts/DMA                                 : 
**            Common Tx/Rx interrupt                       : 
**              Interrupt                                  : INT_UART0_RX_TX
**              Interrupt request                          : Enabled
**              Interrupt priority                         : 16
**              ISR name                                   : UARTRX
**              Transmit empty request                     : Disabled
**              Transmit empty request type                : IRQ
**              Transmit complete request                  : Disabled
**              Receiver full request                      : Enabled
**              Receiver full request type                 : IRQ
**              Idle line request                          : Disabled
**              LIN break detect request                   : Disabled
**              Rx active edge interrupt                   : Disabled
**              Smartcards interface (ISO7816) interrupts  : 
**                Init char detected interrupt             : Disabled
**            Error Interrupt                              : 
**              Error interrupt                            : INT_UART0_ERR
**              Interrupt request                          : <Automatic>
**              Interrupt priority                         : <Automatic>
**              ISR name                                   : 
**              Overrun error interrupt                    : Disabled
**              Noise error interrupt                      : Disabled
**              Framing error interrupt                    : Disabled
**              Parity error interrupt                     : Disabled
**              FIFOs interrupts                           : 
**                Tx FIFO overflow interrupt               : Disabled
**                Rx FIFO underflow interrupt              : Disabled
**                Rx FIFO overflow interrupt               : Disabled
**              Smartcards interface (ISO7816) interrupts  : 
**                Wait timer interrupt                     : Disabled
**                Char wait timer interrupt                : Disabled
**                Block wait timer interrupt               : Disabled
**                Tx threshold exceeded interrupt          : Disabled
**                Rx threshold exceeded                    : Disabled
**                Guard timer violated interrupt           : Disabled
**          Initialization                                 : 
**            Send break                                   : Disabled
**            Enable transmitter                           : Enabled
**            Enable receiver                              : Enabled
**            Call Init method                             : yes
**            Utilize after reset values                   : default
**     Contents    :
**         Init - void UART0_Init(void);
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file UART0_Config.h                                                  
** @version 01.07
** @brief
**          This file implements the UART (UART0) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
*/         
/*!
**  @addtogroup UART0_Config_module UART0_Config module documentation
**  @{
*/         

#ifndef UART0_Config_H_
#define UART0_Config_H_

/* MODULE UART0. */

/* UART0_C2: TE=0,RE=0 */
#define UART0_C2_VALUE_1     0x00U
#define UART0_C2_MASK_1      0x0CU
/* UART0_BDH: LBKDIE=0,RXEDGIE=0,??=0,SBR=0 */
#define UART0_BDH_VALUE      0x00U
/* UART0_BDL: SBR=0x41 */
#define UART0_BDL_VALUE      0x41U
/* UART0_C4: MAEN1=0,MAEN2=0,M10=0,BRFA=3 */
#define UART0_C4_VALUE       0x03U
/* UART0_MA1: MA=0 */
#define UART0_MA1_VALUE      0x00U
/* UART0_MA2: MA=0 */
#define UART0_MA2_VALUE      0x00U
/* UART0_C1: LOOPS=0,UARTSWAI=0,RSRC=0,M=0,WAKE=0,ILT=0,PE=0,PT=0 */
#define UART0_C1_VALUE       0x00U
/* UART0_S2: LBKDIF=1,RXEDGIF=1,MSBF=0,RXINV=0,RWUID=0,BRK13=0,LBKDE=0,RAF=0 */
#define UART0_S2_VALUE       0xC0U
/* UART0_MODEM: ??=0,??=0,??=0,??=0,RXRTSE=0,TXRTSPOL=0,TXRTSE=0,TXCTSE=0 */
#define UART0_MODEM_VALUE    0x00U
/* UART0_IR: ??=0,??=0,??=0,??=0,??=0,IREN=0,TNP=0 */
#define UART0_IR_VALUE       0x00U
/* UART0_TWFIFO: TXWATER=0 */
#define UART0_TWFIFO_VALUE   0x00U
/* UART0_RWFIFO: RXWATER=1 */
#define UART0_RWFIFO_VALUE   0x01U
/* UART0_SFIFO: TXEMPT=1,RXEMPT=1,??=0,??=0,??=0,RXOF=1,TXOF=1,RXUF=1 */
#define UART0_SFIFO_VALUE    0xC7U
/* UART0_CFIFO: TXFLUSH=1,RXFLUSH=1,??=0,??=0,??=0,RXOFE=0,TXOFE=0,RXUFE=0 */
#define UART0_CFIFO_VALUE    0xC0U
#define UART0_CFIFO_MASK     0xFFU
/* UART0_PFIFO: TXFE=0,RXFE=0 */
#define UART0_PFIFO_VALUE    0x00U
#define UART0_PFIFO_MASK     0x88U
/* UART0_ET7816: TXTHRESHOLD=0,RXTHRESHOLD=0 */
#define UART0_ET7816_VALUE   0x00U
/* UART0_WF7816: GTFD=1 */
#define UART0_WF7816_VALUE   0x01U
/* UART0_WN7816: GTN=0 */
#define UART0_WN7816_VALUE   0x00U
/* UART0_AP7816B_T0: ADTI_L=0 */
#define UART0_AP7816B_T0_VALUE 0x00U
/* UART0_AP7816A_T0: ADTI_H=0 */
#define UART0_AP7816A_T0_VALUE 0x00U
/* UART0_WP7816B_T0: WI_L=0x14 */
#define UART0_WP7816B_T0_VALUE 0x14U
/* UART0_WP7816A_T0: WI_H=0 */
#define UART0_WP7816A_T0_VALUE 0x00U
/* UART0_IS7816: WT=1,CWT=1,BWT=1,INITD=1,ADT=0,GTV=1,TXT=1,RXT=1 */
#define UART0_IS7816_VALUE   0xF7U
/* UART0_IE7816: WTE=0,CWTE=0,BWTE=0,INITDE=0,ADTE=0,GTVE=0,TXTE=0,RXTE=0 */
#define UART0_IE7816_VALUE   0x00U
/* UART0_C7816: ??=0,??=0,??=0,ONACK=0,ANACK=0,INIT=0,TTYPE=0,ISO_7816E=0 */
#define UART0_C7816_VALUE    0x00U
#define UART0_C7816_MASK     0xFFU
#define UART0_CLEAR_FLAGS
/* UART0_C5: TDMAS=0,??=0,RDMAS=0,??=0,??=0,??=0,??=0 */
#define UART0_C5_VALUE       0x00U
#define UART0_C5_MASK        0xEFU
/* UART0_C3: R8=0,T8=0,TXDIR=0,TXINV=0,ORIE=0,NEIE=0,FEIE=0,PEIE=0 */
#define UART0_C3_VALUE       0x00U
/* UART0_C2: TIE=0,TCIE=0,RIE=1,ILIE=0,TE=1,RE=1,RWU=0,SBK=0 */
#define UART0_C2_VALUE_2     0x2CU

#define UART0_AUTOINIT

#define INT_UART0_RX_TX_ISR UARTRX

/* END UART0. */
#endif /* #ifndef __UART0_Config_H_ */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
