/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : SPI0.c
**     Project     : RF_Remote_Code
**     Processor   : MKL25Z64VLH4
**     Component   : Init_SPI
**     Version     : Component 01.001, Driver 01.01, CPU db: 3.00.000
**     Repository  : Kinetis
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-12-30, 18:06, # CodeGen: 60
**     Abstract    :
**          This file implements the SPI (SPI0) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
**     Settings    :
**          Component name                                 : SPI0
**          Device                                         : SPI0
**          Settings                                       : 
**            Clock gate                                   : Enabled
**            Clock setting                                : 
**              Baud rate prescaler                        : divide by 1
**              Baud rate divisor                          : divide by 4
**              SCK frequency                              : 6 MHz
**            Mode Select                                  : Master
**            Clock polarity                               : Active-low
**            Clock phase                                  : Second edge
**            Data shift order                             : MSB first
**            Bidirectional mode                           : Disabled
**            Output enable in bidirect. mode              : no
**            SS pin function                              : Automatic Slave Select output
**            Match value                                  : 0
**            Stop in wait mode                            : Disabled
**          Pins                                           : 
**            SCK pin allocation                           : Enabled
**              SCK pin                                    : ADC0_SE5b/PTD1/SPI0_SCK/TPM0_CH1
**              SCK pin signal                             : 
**            MISO pin allocation                          : Enabled
**              MISO pin                                   : PTD3/SPI0_MISO/UART2_TX/TPM0_CH3/SPI0_MOSI
**              MISO pin signal                            : 
**            MOSI pin allocation                          : Enabled
**              MOSI pin                                   : PTD2/SPI0_MOSI/UART2_RX/TPM0_CH2/SPI0_MISO
**              MOSI pin signal                            : 
**            SS pin allocation                            : Disabled
**          Interrupts/DMA                                 : 
**            SPI interrupt/DMA                            : 
**              Interrupt                                  : INT_SPI0
**              Interrupt request                          : Disabled
**              Interrupt priority                         : 0 (Highest)
**              ISR Name                                   : 
**              Receive and fault interrupt                : Disabled
**              Receive DMA                                : Disabled
**              Transmit interrupt                         : Disabled
**              Transmit DMA                               : Disabled
**              Match interrupt                            : Disabled
**          Initialization                                 : 
**            Module enable                                : yes
**            Call Init method                             : yes
**     Contents    :
**         Init - void SPI0_Init(void);
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file SPI0.c
** @version 01.01
** @brief
**          This file implements the SPI (SPI0) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
*/         
/*!
**  @addtogroup SPI0_module SPI0 module documentation
**  @{
*/         

/* MODULE SPI0. */

#include "SPI0.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"


/*
** ===================================================================
**     Method      :  SPI0_Init (component Init_SPI)
**     Description :
**         This method initializes registers of the SPI module
**         according to the Peripheral Initialization settings.
**         Call this method in user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void SPI0_Init(void)
{
  /* SIM_SCGC4: SPI0=1 */
  SIM_SCGC4 |= SIM_SCGC4_SPI0_MASK;
  /* SPI0_C1: SPIE=0,SPE=0,SPTIE=0,MSTR=0,CPOL=0,CPHA=1,SSOE=0,LSBFE=0 */
  SPI0_C1 = SPI_C1_CPHA_MASK;
  /* SPI0_C2: SPMIE=0,TXDMAE=0,MODFEN=1,BIDIROE=0,RXDMAE=0,SPISWAI=0,SPC0=0 */
  SPI0_C2 = (uint8_t)((SPI0_C2 & (uint8_t)~(uint8_t)(
             SPI_C2_SPMIE_MASK |
             SPI_C2_TXDMAE_MASK |
             SPI_C2_BIDIROE_MASK |
             SPI_C2_RXDMAE_MASK |
             SPI_C2_SPISWAI_MASK |
             SPI_C2_SPC0_MASK
            )) | (uint8_t)(
             SPI_C2_MODFEN_MASK
            ));
  /* SPI0_BR: ??=0,SPPR=0,SPR=1 */
  SPI0_BR = (SPI_BR_SPPR(0x00) | SPI_BR_SPR(0x01));
  /* SPI0_M: Bits=0 */
  SPI0_M = SPI_M_Bits(0x00);
  /* SPI0_C1: SPIE=0,SPE=1,SPTIE=0,MSTR=1,CPOL=1,CPHA=1,SSOE=1,LSBFE=0 */
  SPI0_C1 = SPI_C1_SPE_MASK |
            SPI_C1_MSTR_MASK |
            SPI_C1_CPOL_MASK |
            SPI_C1_CPHA_MASK |
            SPI_C1_SSOE_MASK;
}


/* END SPI0. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
