/*
 * FC.c
 *
 *  Created on: Nov 14, 2015
 *      Author: Z
 */

#include "FC.h"

GPIO_HANDLES BLUE_PIN = {PORTA,5,GPIO_OUTPUT};
GPIO_HANDLES RED_PIN = {PORTA,12,GPIO_OUTPUT};
GPIO_HANDLES GREEN_PIN = {PORTA,13,GPIO_OUTPUT};

GPIO_HANDLES AUX1 = {PORTB,3,GPIO_OUTPUT};
GPIO_HANDLES AUX2 = {PORTB,2,GPIO_OUTPUT};

GPIO_HANDLES PWM0 = {PORTC,1,GPIO_OUTPUT};
GPIO_HANDLES PWM1 = {PORTC,2,GPIO_OUTPUT};
GPIO_HANDLES PWM2 = {PORTC,3,GPIO_OUTPUT};
GPIO_HANDLES PWM3 = {PORTC,4,GPIO_OUTPUT};

//MPU92500 SPI :: SPI0
GPIO_HANDLES SCLK2 = {PORTC,5,GPIO_OUTPUT};
GPIO_HANDLES MOSI2 = {PORTC,6,GPIO_OUTPUT};
GPIO_HANDLES MISO2 = {PORTC,7,GPIO_OUTPUT};
GPIO_HANDLES MPU_INT = {PORTC,8,GPIO_OUTPUT};
GPIO_HANDLES MPU9250_CS = {PORTC,9,GPIO_OUTPUT};

//CC2500 SPI1
GPIO_HANDLES CC_CS_PIN = {PORTD,2,GPIO_OUTPUT};
GPIO_HANDLES GDO0 = {PORTD,3,GPIO_OUTPUT};
GPIO_HANDLES GDO2 = {PORTD,4,GPIO_OUTPUT};
GPIO_HANDLES SCLK1 = {PORTD,5,GPIO_OUTPUT};
GPIO_HANDLES MOSI1 = {PORTD,6,GPIO_OUTPUT};
GPIO_HANDLES MISO1 = {PORTD,7,GPIO_OUTPUT};

GPIO_HANDLES A1 = {PORTB,3,GPIO_OUTPUT};
GPIO_HANDLES A2 = {PORTB,2,GPIO_OUTPUT}; // In use


//GPIO_HANDLES MISO1 = {PORTD,7,GPIO_OUTPUT};

uint8_t USB_RDY = 0;

void Init_FC_IO()
{
	GPIO_Enable_All_Ports();

	Setup_Pin(&BLUE_PIN);
	//Setup_Pin(&RED_PIN); //Comment this out if using PWM
	//Setup_Pin(&GREEN_PIN);

	Setup_Pin(&MPU9250_CS);
	Setup_Pin(&CC_CS_PIN);
	Setup_Pin(&A1);

	Set_Pin(&BLUE_PIN,1);
	//Set_Pin(&RED_PIN,1);
	//Set_Pin(&GREEN_PIN,1);

	Set_Pin(&MPU9250_CS,1);
	Set_Pin(&CC_CS_PIN,1);

}
